---
# tasks file for serverTools
- name: set a hostname
  hostname:
    name: "{{ hostname }}"
  notify: 
    - addInHostsFile

- name: 'Role: serverTools Softwares uteis para administracao do servidor - Ubuntu'
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - vim
      - iftop
      - zip
      - wget 
      - curl
      - python3
      - python3-pip
    #  - yum-utils
    state : latest
  when: (ansible_facts['os_family'] == "Debian")
  #notify: 
  #  - enable yum-utils

- name: 'Permite trafego http no firewalld do CentOS'
  firewalld:
    service: http
    permanent: yes
    state: enabled
  when: (ansible_facts['os_family'] == "RedHat")

- name: 'Disable SELinux em sistemas derivados do RedHat'
  selinux:
    state: disabled
  when: (ansible_facts['os_family'] == "RedHat")
  notify: 
    - Restart Server