---
# tasks file for apache
- name: Inclui debian.yml
  import_tasks: debian.yml
  when: (ansible_facts['os_family'] == "Debian")

- name: "Cria diretorio que ira hospedar os arquivos do site"
  file:
    path: " {{site_folder }}"
    state: directory
    mode: '0755'
  
- name: "Copia arquivo index.html simples"
  copy:
    src: index.html
    dest: "{{ site_folder }}"